server:
  port: 8443
spring:
  application:
    name: cyber-gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 120.79.254.225:8848
    gateway:
      routes:
         #系统服务
         - id: neo4j
           uri: lb://cyber-neo4j-service2
           predicates:
             - Path=/neo4jservice/**
           filters:
             - StripPrefix=1
         #系统服务
         - id: system
           uri: lb://cyber-system-service2
           predicates:
             - Path=/systemservice/**
           filters:
             - StripPrefix=1
  activemq:
    pool:
      maximum-active-session-per-connection:100
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.79.254.225:3306/mysql
    username: root
    password: 84737866CRy
mybatis-plus:
  mapper-locations: classpath*:com/example/cyberPunk/**/xml/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: ASSIGN_ID
      table-underline: true

